#!/usr/bin/env bash
# Compile-probe upstream's game sources for Android arm64-v8a, WITHOUT
# needing the generated game code (no game dump, no codegen, no device).
#
# It compiles exactly the source list upstream's CMakeLists puts into the
# `reeot` target (REEOT_SOURCES), with the NDK clang for arm64, except:
#   - src/main.cpp and src/reeot_app.cpp, which #include generated headers
#     (reported separately as "needs codegen" - expected failures);
#   - platform/moltenvk.cpp (macOS-only, only added on APPLE).
#
# This is the fast, no-secrets regression gate for the upstream Android port
# (patches/upstream/): "does the game code compile for Android". Failures here
# are real porting work; the two codegen-dependent files are documented.
#
# Run from the repository root. Requires ANDROID_HOME (GitHub runners set it).
set -uo pipefail

NDK_VERSION="${NDK_VERSION:-27.3.13750724}"
API="${API:-28}"
NDK="${ANDROID_HOME:?ANDROID_HOME not set}/ndk/$NDK_VERSION"
CXX="$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android${API}-clang++"

SDK="thirdparty/rexglue-sdk"
UP="upstream"
GEN="out/probe-gen"
mkdir -p "$GEN/core" out

# Minimal generated headers the sources include.
cat > "$GEN/core/build_info.h" <<'HDR'
#pragma once
#define REEOT_VERSION_STRING  "0.0.0-probe"
#define REEOT_GIT_COMMIT      "probe"
#define REEOT_GIT_BRANCH      "probe"
#define REEOT_GIT_DIRTY       0
#define REEOT_BUILD_PLATFORM  "android-arm64"
#define REEOT_BUILD_COMPILER  "probe"
#define REEOT_BUILD_TIMESTAMP "00000000_0000"
HDR

# Stub the build-time-generated host shader headers (normally produced by
# reeot_host_shader() via dxc). The real build compiles the HLSL with dxc; the
# probe only checks that the C++ compiles, so 1-byte placeholder arrays with
# the same symbol names (g_<stem>_spirv / g_<stem>_dxil) are sufficient.
mkdir -p "$GEN/shaders"
for hlsl in "$UP"/src/gpu/shaders/hlsl/*.hlsl; do
    stem="$(basename "$hlsl" .hlsl)"
    printf '#pragma once\nconst unsigned char g_%s_spirv[] = {0};\n' "$stem" > "$GEN/shaders/$stem.hlsl.spirv.h"
    printf '#pragma once\nconst unsigned char g_%s_dxil[] = {0};\n' "$stem"  > "$GEN/shaders/$stem.hlsl.dxil.h"
done

# Stub the SDK's configured version header (normally generated from
# include/rex/version.h.in by the SDK's CMake configure).
mkdir -p "$GEN/rex"
cat > "$GEN/rex/version.h" <<'HDR'
#pragma once
#define REXGLUE_VERSION_MAJOR 0
#define REXGLUE_VERSION_MINOR 10
#define REXGLUE_VERSION_PATCH 0
#define REXGLUE_VERSION_TWEAK 0
#define REXGLUE_VERSION_STRING "0.10.0-probe"
#define REXGLUE_VERSION_NUMERIC "0.10.0"
#define REXGLUE_VERSION_FLOOR "0.10.0"
#define REXGLUE_VERSION_CHANNEL "release"
#define REXGLUE_BUILD_PLATFORM "android-arm64"
#define REXGLUE_BUILD_TIMESTAMP "00000000_0000"
#define REXGLUE_BUILD_TITLE \
  "[rexglue-v" REXGLUE_VERSION_STRING "-" REXGLUE_BUILD_CONFIG "]"
#define REXGLUE_BUILD_STAMP \
  "build: rexglue-v" REXGLUE_VERSION_STRING "-" REXGLUE_BUILD_PLATFORM \
  "-" REXGLUE_BUILD_CONFIG "@" REXGLUE_BUILD_TIMESTAMP
HDR

# Stub the embedded-asset headers (normally generated by cmake/embed.cmake
# from res/embed and the pkz packages). Same public shape as the real thing.
cat > "$GEN/embedded.h" <<'HDR'
#pragma once
#include <cstddef>
#include <cstdint>
#include <span>
#include <string_view>
namespace eot {
struct EmbeddedAsset {
  std::string_view name;
  const uint8_t *data;
  size_t size;
  std::span<const uint8_t> bytes() const { return {data, size}; }
  std::string_view text() const {
    return {reinterpret_cast<const char *>(data), size};
  }
};
inline constexpr EmbeddedAsset kEmbeddedAssets[] = {};
namespace detail { void NoSuchEmbeddedAsset(); }
consteval EmbeddedAsset Embedded(std::string_view) { return {}; }
}  // namespace eot
HDR
for pkg in port menu achievements icons suits; do
    cap="$(echo "$pkg" | sed 's/.*/\U&/')"
    printf '#pragma once\n#include "embedded.h"\nnamespace eot {\ninline EmbeddedAsset Embedded%sPackage() { return {}; }\n}  // namespace eot\n' "$cap" > "$GEN/embedded_${pkg}_package.h"
done

# The HUD aspect policy is generated from config/eot_hud_aspect.toml by a
# committed Python script - run the real generator, no stub needed.
if command -v python3 > /dev/null; then
    python3 "$UP/tools/hud/gen_hud_policy.py" "$UP/config/eot_hud_aspect.toml"         "$GEN/hud_aspect_policy.inc" 2>/dev/null         || echo "// probe stub" > "$GEN/hud_aspect_policy.inc"
else
    echo "// probe stub" > "$GEN/hud_aspect_policy.inc"
fi

INCLUDES=(
    -I"$UP/src"
    -I"$GEN"
    -I"$SDK/include"
    -I"$SDK/thirdparty/sdl3/include"
    -I"$SDK/thirdparty/spdlog/include"
    -I"$SDK/thirdparty/fmt/include"
    -I"$SDK/thirdparty/simde"
    -I"$SDK/thirdparty/vulkan-headers/include"
    -I"$SDK/thirdparty/imgui"
    -I"$UP/thirdparty/renderdoc"
    -I"$UP/thirdparty/XenosRecomp/thirdparty/smol-v/source"
    -I"$UP/thirdparty/XenosRecomp/XenosRecomp"
    -I"$UP/thirdparty/plume/contrib/volk"
    -I"$SDK/thirdparty/xxHash"
    -I"$SDK/thirdparty/vulkan-memory-allocator/include"
    -I"$SDK/thirdparty/tomlplusplus/include"
    -I"$UP/thirdparty/XenosRecomp/thirdparty/zstd/lib"
    -I"$PWD/android/rex_android/include"
)
# plume (Vulkan renderer interface) and imgui live in different places.
for d in "$UP/thirdparty/plume" "$SDK/thirdparty/plume" "$SDK/thirdparty/imgui"; do
    [ -d "$d" ] && INCLUDES+=(-I"$d")
done

FLAGS=(
    -std=c++23
    -fexperimental-library
    -fno-char8_t
    -ffp-model=strict
    -DREX_HAS_VULKAN=1
    -DREEOT_VERSION_STRING='"0.0.0-probe"'
    -DREXGLUE_BUILD_CONFIG='"Release"'
    -c
)

# The exact REEOT_SOURCES list from upstream/CMakeLists.txt.
SOURCES=$(awk '/^set\(REEOT_SOURCES/,/^\)/' "$UP/CMakeLists.txt" \
    | grep -oE 'src/[A-Za-z0-9_/]+\.cpp' | sort -u)

pass=0
fail=0
failed_files=()
for src in $SOURCES; do
    case "$src" in
        src/main.cpp|src/reeot_app.cpp)
            echo "SKIP  $src  (needs codegen output: generated/default/reeot_init.h)"
            continue
            ;;
        src/platform/moltenvk.cpp)
            echo "SKIP  $src  (macOS-only)"
            continue
            ;;
    esac
    [ -f "$UP/$src" ] || { echo "MISS  $src (listed but absent)"; continue; }
    name="$(echo "$src" | tr '/' '_')"
    if "$CXX" "${FLAGS[@]}" "${INCLUDES[@]}" "$UP/$src" -o /dev/null 2> "out/probe-$name.err"; then
        echo "PASS  $src"
        pass=$((pass + 1))
    else
        echo "FAIL  $src"
        grep -m4 "error:" "out/probe-$name.err" | sed 's/^/      /'
        fail=$((fail + 1))
        failed_files+=("$src")
    fi
done

echo ""
echo "upstream Android compile probe: $pass passed, $fail failed"
if [ "$fail" -gt 0 ]; then
    echo "failed files:"
    printf '  %s\n' "${failed_files[@]}"
    exit 1
fi
exit 0
